### ISSUE TITLE
Merge Tool : Request , preserve right click for navigation 

### ISSUE THREAD

**Issue by AMYO77** [Stromberg90/Scripts#23]
A tiny request, can "right click"  "left click" and "alt" be preserved for navigation to work around the mesh without the need to exit and re_enter the tool, maybe as an addon preferences ?

Now i understand ,this will need a little more work than what i was thinking.

An ideal workflow will be : 

M or( something else) to enter the tool .
Esc to exit the tool.

I understand also that adding ctrl+z inside the tool will require more work, but it's not that a big deal since you can exit the tool and then ctrl+z.

**Comment by lukaschrapek** [comment]
It would be nice to preserve viewport navigation for Industry Standart layout, when you hold "ALT' and left, right middle mouse click for navigation, then left click to merge and right click to exit tool.

**Comment by MightyBOBcnc** [comment]
I just added a quick change to add Industry Alt-key navigation support.  [Download version 1.1.1](https://github.com/Stromberg90/Scripts/raw/master/Blender/MergeTool.py)

FYI I'm working on a major update to the Merge Tool at the moment that will: 
- make it an actual tool on the left side toolbar,
- add support for edge merging,
- have a number of preferences like choosing to merge at the first/last/center and user-configurable overlay colors,
- and won't have issues with Ctrl+Z not being functional while you're using the tool.

I'm hoping that I can maybe have the big update ready before this month is over.

**Comment by AMYO77** [comment]
Amazing news, thank you !

**Comment by lukaschrapek** [comment]
Great news. Thank you.

I looking forward to new update. Edge support would be amazing, also if you looking for suggestions, for example in Maya Merge Tool, you can also make selection of  multiple vertexes then when you activate Merge tool, tool is remembering that selection and you can merge that vertexes to any other vert base where you drag, but is just suggestion :)

![MergeTool_001](https://user-images.githubusercontent.com/44464495/103465516-9ea63000-4d3c-11eb-91dc-ab3864bf9818.gif)

**Comment by AMYO77** [comment]
I'm trying beta version with edge support, this is very nice, would you like some help on the icon part ?
(that's the only part i know i can help) I can do it for free, this should be quick, i'll try to make it look "blender vanilla".

**Comment by MightyBOBcnc** [comment]
Are you getting the beta build from my personal/experimental branch or from discord?  I did make a toolbar icon for the tool but you need to install the build as a zip file or else you'll have to manually add the icons folder in your scripts\addons\mesh_merge_tool folder:
![image](https://user-images.githubusercontent.com/4467749/103595366-3c2e6a80-4ec9-11eb-8474-f0a6834e8872.png)

I borrowed and modified the icon from the built in Vertex Slide tool.

![image](https://user-images.githubusercontent.com/4467749/103594088-ab09c480-4ec5-11eb-8530-3a457dfbb421.png)
(I actually need to share my source file for the icon once I push the update in order to be GPL compliant.)

But really if you have a suggestion for something better I'm open to ideas.  The [2.80 Tool Icon Design task](https://developer.blender.org/T54662) came up with the visual language that Green = Add, Purple = Deform, and Red = Remove but it didn't really come up with a language color for "Merge".  Merge is sort of like Remove but it does also "Add" new geometry at the end of an operation.

There is an [official guide](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/UI_DESIGN#Toolbar_Icons) for how to make a toolbar icon but frankly it isn't very helpful and it seems to require downloading the entire Blender source code and running build scripts from the command line.

None of that is strictly needed, though.  In 3 simple steps you can just download [the icon file](https://svn.blender.org/svnroot/bf-blender/trunk/lib/resources/) from Blender's SVN, then create/edit an icon, then copy/paste and run their [icon building script](https://github.com/blender/blender/blob/master/release/datafiles/blender_icons_geom.py) from inside Blender itself in the Script Editor.  This will dump all the icons from the .blend file into Blender's root folder (the folder that contains blender.exe) as Blender's .dat format icons.  Then you can just grab the icon .dat file you need and put it in the right folder.  (It might be easier to just delete all the icons inside the blend file that you don't need because it will build ALL of them.)

![image](https://user-images.githubusercontent.com/4467749/103595129-adb9e900-4ec8-11eb-8990-5fef7de5001c.png)

**Comment by AMYO77** [comment]
You nailed it, i was just happy to help, i might have a version without the icon, i'll check to see if you're already updated it/

Thanks again for your work.

I'm taking it from the experimental branch, i didn't knew  you could get it on discord.

**Comment by MightyBOBcnc** [comment]
> i didn't knew you could get it on discord.

I've been sharing zipped beta builds on the Bforartists discord.

Here's an example of the file structure inside the zip file (this version now has user-configurable colors in the add-on preferences).
[mesh_merge_tool.zip](https://github.com/Stromberg90/Scripts/files/5767669/mesh_merge_tool.zip)

`MergeTool.py` gets renamed to `__init__.py`, which goes inside a mesh_merge_tool folder, and inside there is the icons folder with the icon .dat file.

![image](https://user-images.githubusercontent.com/4467749/103597992-8f0b2080-4ecf-11eb-9ee2-8a4da00fd757.png)

**Comment by AMYO77** [comment]
This is perfect, no issue with ctrl+Z so far, edge merging is working great.
I can shortcut the tool no problem, settings are already there.

I mean if you add merging multiples vertices ( and maybe i'm wrong but from what i see with the cursor, i think you're already on it), it will be the perfect tool, it is so much better even in his beta state.

Thanks again.

**Comment by MightyBOBcnc** [comment]
New beta 1.1.8 with better viewport overlay drawing (especially edge mode) and a couple extra settings in the Preferences to control line width and point size.  Also it doesn't spam up the console with print statements.

[mesh_merge_tool.zip](https://github.com/Stromberg90/Scripts/files/5798835/mesh_merge_tool.zip)

**Comment by AMYO77** [comment]
Everything is working so far, it feels more polished.

**Comment by MightyBOBcnc** [comment]
I'm going to close this since the right click / Industry navigation has been fixed and the latest 1.2.0 is released.  Grab the .zip file to install.  Readme.md has also been updated with new info and keys:
https://github.com/Stromberg90/Scripts/tree/master/Blender

@lukaschrapek Multi-vert merge from a starting selection is on my ToDo list.

**Comment by MightyBOBcnc** [comment]
@lukaschrapek Multi-vert merge is now available in 1.3.0

**Comment by AMYO77** [comment]
I knew  you were already on it, mouahaha.
You rock man.
Thanks for your work.
