### ISSUE TITLE
Edges to curves Blender 2.90.1

### ISSUE THREAD

**Issue by Thatcher64** [Stromberg90/Scripts#24]
the plugin installs fine, but it doesn't seem to work with the latest version of Blender 2.90.1. It does not show up in the search function.

**Comment by MightyBOBcnc** [comment]
This is likely due to a change in the way Blender handles search in the latest releases. 
https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API#Compatibility

The edge to curve operator should probably be added to a menu so that it can be searched.  Perhaps append it to the end of `VIEW3D_MT_edit_mesh_edges`

(As an aside, the Duplicate Along Curve add-on might need the same treatment although I'm not sure which menu to put it in; VIEW3D_MT_object maybe, but you can't insert in the middle of a menu with the other Duplicate commands, only at the beginning or end of the list.)

**Comment by MightyBOBcnc** [comment]
@Thatcher64 Try this version: https://github.com/Stromberg90/Scripts/raw/master/Blender/Edge_To_Curve.py

**Comment by MightyBOBcnc** [comment]
Merged fix into master.
