### ISSUE TITLE
Support Merge tool for Blender4

### ISSUE THREAD

**Issue by kloworks** [Stromberg90/Scripts#37]
Hi, 
hope we can get updates for all tools, 
merge tool kind work but it lost the preview before merge 

thanks

**Comment by MightyBOBcnc** [comment]
Checking in 4.0 shows that functionally the tool works (merging still works as expected) but yes the assisting lines and dots are not rendering.  I thought the `gpu` module was going to be stable after the changes needed for #36 but it looks like they changed something again.  This error pops up in the console while running the merge tool:

```
Traceback (most recent call last):
  File "C:\Portable\blender-4.0.0-windows-x64\4.0\scripts\addons\mesh_merge_tool\__init__.py", line 250, in draw_callback_3d
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'
```

Probably an easy fix and I just need to make sure that any fix for 4.0 keeps working in older versions of Blender.

**Comment by MightyBOBcnc** [comment]
This appears to be the culprit: https://projects.blender.org/blender/blender/commit/9a8fd2f1ddb491892297315a4f76b6ed2b0c1b94 

The fix may be as simple as changing line 250 from `3D_UNIFORM_COLOR` to `UNIFORM_COLOR` and to test backward compatibility.  

Reference: https://projects.blender.org/blender/blender/issues/114359

-Edit: Had to add a small conditional check as versions less than 3.4 don't support `UNIFORM_COLOR` but otherwise it was indeed a 1-line fix.

**Comment by MightyBOBcnc** [comment]
Give this a shot: 

https://github.com/Stromberg90/Scripts/blob/master/Blender/mesh_merge_tool.zip

**Comment by kloworks** [comment]
all good now, Thank you so much
